In [10]:
import numpy as np
from fractions import Fraction
R = int(input("Enter the number of rows\n"))
C = int(input("Enter the number of columns\n"))
k=C*R
print("Enter the ",k,"entries in a single line (separated by space) of first matrix\n ")
entries1 = list(map(int, input().split()))
matrix1 = np.array(entries1).reshape(R, C)
print("Enter the ",k,"entries in a single line (separated by space) of second matrix\n ")
entries2 = list(map(int, input().split()))
matrix2 = np.array(entries2).reshape(R, C)
print(matrix1)
print(matrix2)
dot=np.dot(matrix1,matrix2)
print("\n")
print("dot product of two matrix is :\n",dot)
print("\n")
print("transpose of dot product is :\n",np.transpose(dot))
print("\n")
print("trace of dot product is :\n",np.trace(dot))
print("\n")
print("RANK of dot product is :\n",np.linalg.matrix_rank(dot))
print("\n")
print("DETERMINANT of dot product is :\n",int(np.linalg.det(dot)))
print("\n")
print("inverse of dot product is :\n",np.linalg.inv(dot))
print("\n")
print("eigen values of dot product is :\n",np.linalg.eig(dot))

Enter the number of rows
 2
Enter the number of columns
 2


Enter the  4 entries in a single line (separated by space) of first matrix
 


 4 5 6 7


Enter the  4 entries in a single line (separated by space) of second matrix
 


 4 8 9 1


[[4 5]
 [6 7]]
[[4 8]
 [9 1]]


dot product of two matrix is :
 [[61 37]
 [87 55]]


transpose of dot product is :
 [[61 87]
 [37 55]]


trace of dot product is :
 116


RANK of dot product is :
 2


DETERMINANT of dot product is :
 136


inverse of dot product is :
 [[ 0.40441176 -0.27205882]
 [-0.63970588  0.44852941]]


eigen values of dot product is :
 (array([114.81549085,   1.18450915]), array([[ 0.56654806, -0.52606023],
       [ 0.8240287 ,  0.85044732]]))
